# Generated by Django 4.0.4 on 2022-04-26 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nearin_app', '0002_rename_shop_register_shop_login_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShopName', models.CharField(max_length=25)),
                ('Delivery', models.CharField(choices=[('y', 'yes'), ('n', 'no')], max_length=10)),
                ('City', models.CharField(max_length=25)),
                ('State', models.CharField(max_length=25)),
                ('Pincode', models.CharField(max_length=25)),
                ('Address', models.TextField(max_length=250)),
                ('Shop_login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nearin_app.shop_login')),
            ],
            options={
                'db_table': 'shop_profile',
            },
        ),
    ]
