# Generated by Django 4.0.4 on 2022-04-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nearin_app', '0003_shop_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_profile',
            name='Address',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='shop_profile',
            name='City',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='shop_profile',
            name='Pincode',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='shop_profile',
            name='ShopName',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='shop_profile',
            name='State',
            field=models.CharField(default='', max_length=25),
        ),
    ]
