# Generated by Django 4.0.4 on 2022-04-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nearin_app', '0004_alter_shop_profile_address_alter_shop_profile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_profile',
            name='ShopImage',
            field=models.FileField(default='images/shop.png', upload_to='images/shops'),
        ),
    ]
