# Generated by Django 4.0.4 on 2022-04-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nearin_app', '0005_shop_profile_shopimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_profile',
            name='Contact',
            field=models.TextField(default='', max_length=12),
        ),
    ]
