# Generated by Django 4.0.4 on 2022-04-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nearin_app', '0006_shop_profile_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cust_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustEmail', models.CharField(max_length=25)),
                ('CustPassword', models.CharField(max_length=12)),
                ('IsActive', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cust_login',
            },
        ),
    ]
