# Generated by Django 4.0.4 on 2022-04-29 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nearin_app', '0007_cust_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cust_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShopImage', models.FileField(default='images/shop.png', upload_to='images/shops')),
                ('ShopName', models.CharField(default='', max_length=25)),
                ('Delivery', models.CharField(choices=[('y', 'yes'), ('n', 'no')], max_length=10)),
                ('City', models.CharField(default='', max_length=25)),
                ('State', models.CharField(default='', max_length=25)),
                ('Pincode', models.CharField(default='', max_length=25)),
                ('Address', models.TextField(default='', max_length=250)),
                ('Contact', models.TextField(default='', max_length=12)),
                ('Shop_login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nearin_app.shop_login')),
            ],
            options={
                'db_table': 'Cust_profile',
            },
        ),
    ]
