# Generated by Django 4.0.4 on 2022-04-29 21:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nearin_app', '0008_cust_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cust_profile',
            name='Shop_login',
        ),
        migrations.AddField(
            model_name='cust_profile',
            name='Cust_login',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nearin_app.cust_login'),
            preserve_default=False,
        ),
    ]
