# Generated by Django 4.0.4 on 2022-04-30 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nearin_app', '0009_remove_cust_profile_shop_login_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=25)),
                ('Password', models.CharField(max_length=12)),
                ('IsActive', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'master',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOB', models.DateField(auto_created=True, default='2022-01-01')),
                ('profileimage', models.FileField(default='images/shop.png', upload_to='images/shops')),
                ('FullName', models.CharField(default='', max_length=25)),
                ('Gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=10)),
                ('City', models.CharField(default='', max_length=25)),
                ('State', models.CharField(default='', max_length=25)),
                ('Pincode', models.CharField(default='', max_length=25)),
                ('Address', models.TextField(default='', max_length=250)),
                ('Contact', models.TextField(default='', max_length=12)),
                ('Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nearin_app.master')),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.RemoveField(
            model_name='cust_profile',
            name='Cust_login',
        ),
        migrations.DeleteModel(
            name='Cust_login',
        ),
        migrations.DeleteModel(
            name='Cust_profile',
        ),
    ]
