# Generated by Django 4.0.4 on 2022-04-30 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nearin_app', '0010_master_profile_remove_cust_profile_cust_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profileimage',
        ),
    ]
