# Generated by Django 4.0.4 on 2022-04-30 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nearin_app', '0012_remove_profile_dob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
