# Generated by Django 4.0.4 on 2022-04-30 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nearin_app', '0014_alter_master_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(default='', max_length=25)),
                ('Gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=10)),
                ('City', models.CharField(default='', max_length=25)),
                ('State', models.CharField(default='', max_length=25)),
                ('Pincode', models.CharField(default='', max_length=25)),
                ('Address', models.TextField(default='', max_length=250)),
                ('Contact', models.TextField(default='', max_length=12)),
                ('Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nearin_app.master')),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
