# Generated by Django 4.0.4 on 2022-04-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nearin_app', '0015_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='DOB',
            field=models.DateField(auto_created=True, default='2022-01-01'),
        ),
    ]
