# Generated by Django 4.0.4 on 2022-05-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nearin_app', '0016_profile_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ProfileImage',
            field=models.FileField(default='images/user.png', upload_to='images/users'),
        ),
    ]
