# Generated by Django 4.0.4 on 2022-05-04 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nearin_app', '0018_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
