# Generated by Django 4.0.4 on 2022-05-04 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nearin_app', '0019_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProName', models.CharField(default='', max_length=25)),
                ('Des', models.TextField(default='', max_length=12)),
                ('Shop_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nearin_app.shop_profile')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
