# Generated by Django 4.0.4 on 2022-05-05 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nearin_app', '0020_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
