# Generated by Django 4.0.4 on 2022-05-05 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nearin_app', '0023_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.CharField(default='', max_length=25)),
            ],
            options={
                'db_table': 'state',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', max_length=25)),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nearin_app.state')),
            ],
            options={
                'db_table': 'city',
            },
        ),
    ]
