# Generated by Django 4.0.4 on 2022-05-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nearin_app', '0025_product_product_type_shop_type_profile_complex_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='State',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Product_type',
        ),
        migrations.DeleteModel(
            name='Shop_type',
        ),
        migrations.AlterField(
            model_name='shop_profile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
