# Generated by Django 4.0.4 on 2022-05-10 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nearin_app', '0026_remove_city_state_delete_product_delete_product_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_type', models.CharField(default='', max_length=25)),
            ],
            options={
                'db_table': 'Product_type',
            },
        ),
        migrations.CreateModel(
            name='Shop_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shop_type', models.CharField(default='', max_length=25)),
            ],
            options={
                'db_table': 'Shop_type',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.CharField(default='', max_length=25)),
            ],
            options={
                'db_table': 'state',
            },
        ),
        migrations.AlterField(
            model_name='shop_profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Image', models.FileField(default='images/product.png', upload_to='images/users')),
                ('Prod_name', models.CharField(default='', max_length=25)),
                ('Prod_type', models.CharField(default='', max_length=25)),
                ('Prod_price', models.FloatField(default='', max_length=25)),
                ('Prod_des', models.TextField(default='', max_length=255)),
                ('Availability', models.CharField(choices=[('y', 'yes'), ('n', 'no')], max_length=10)),
                ('Profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nearin_app.shop_profile')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', max_length=25)),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nearin_app.state')),
            ],
            options={
                'db_table': 'city',
            },
        ),
    ]
