# Generated by Django 4.0.4 on 2022-05-10 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nearin_app', '0027_product_type_shop_type_state_alter_shop_profile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_profile',
            name='DOJ',
            field=models.DateField(default=datetime.datetime(2022, 5, 10, 17, 48, 8, 677939)),
        ),
    ]
