# Generated by Django 4.0.4 on 2022-05-10 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nearin_app', '0028_shop_profile_doj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_profile',
            name='DOJ',
            field=models.DateField(default=datetime.datetime(2022, 5, 10, 17, 56, 54, 811540)),
        ),
    ]
