# Generated by Django 4.0.4 on 2022-05-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nearin_app', '0030_alter_shop_profile_doj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_profile',
            name='DOJ',
            field=models.DateField(auto_now_add=True),
        ),
    ]
